[package]
name = "block-cipher"
version = "0.1.0"
authors = ["royco"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.openssl]
[dependencies.base64]
[dependencies.hamming]