[package]
name = "hex_to_b64"
version = "0.1.0"
authors = ["royco"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.base64]
[dependencies.hex]