[package]
name = "repeating_xor"
version = "0.1.0"
authors = ["royco"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
single_byte_xor = { path = "../single_byte_xor_lib"}
hex=""
hamming=""
